### ISSUE TITLE
java.lang.NoSuchMethodError on Comsat 0.2.0 + Dropwizard 0.7.1

### ISSUE THREAD

**Issue by igor-ye** [puniverse/comsat#16]
Got NoSuchMethodError when trying Comsat 0.2.0 + Dropwizard 0.7.1

Exception in thread "main" java.lang.NoSuchMethodError: io.dropwizard.jersey.setup.JerseyContainerHolder.<init>(Lcom/sun/jersey/spi/container/servlet/ServletContainer;)V
        at io.dropwizard.setup.Environment.<init>(Environment.java:74)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:34)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
        at io.dropwizard.cli.Cli.run(Cli.java:70)
        at io.dropwizard.Application.run(Application.java:72)
        at test.dropwizard.DropWizardServer.main(DropWizardServer.java:39)

But works fine with Dropwizard 0.7.0

As I understand the reason is io.dropwizard.jersey.setup.JerseyContainerHolder bundled together with Comsat. No idea why you include it (and some other dropwizard classes) into distribution.
